version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: magenta-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - magenta-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15
    container_name: magenta-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: magenta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magenta-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: magenta-nginx
    depends_on: []
    ports:
      - "8080:80"               # Public CDN endpoint -> http://localhost:8080
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro   # Local HTML folder
      - ./nginx/conf.d/cdn.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - magenta-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  magenta-network:
    driver: bridge

